### ISSUE TITLE
Problem with duplicates url's

### ISSUE THREAD

**Issue by adrianpaz** [nokaut/white-label-demo#4]
1. Duplicates
produkty-suknie-i-sukienki/
kategoria-suknie-i-sukienki/

1a different count of products
/produkty-buty/
/produkty-produkt:buty.html

2. The same content but different tiles, descriptions
/produkty-suknie-i-sukienki
/produkty-suknie-i-sukienki/

2a.  too many products?
produkty-sukienki-i-koszulki-erotyczne/ 1.7k products
produkty-sukienki-i-koszulki-erotyczne - 69k products

3. Duplicates
/produkty-klapki-damskie/espadryle-tommy-hilfiger-emma-7d-fw56820665-black-990-508bbc5f1794c49ae6189ac2c6f67860
/produkty-klapki-damskie/produkt:espadryle-tommy-hilfiger-emma-7d-fw56820665-black-990.html

4. ???
/produkty-sukienki-i-koszulki-erotyczne/produkt:bluzki-damskie-bluzka-damska-suzi-i.html

**Comment by jjuszkiewicz** [comment]
Url started /produkty- is search result so if you search `/produkty-klapki-damskie/espadryle-tommy-hilfiger-emma-7d-fw56820665-black-990-508bbc5f1794c49ae6189ac2c6f67860` or `/produkty-klapki-damskie/produkt:espadryle-tommy-hilfiger-emma-7d-fw56820665-black-990.html` search engine canonize to this same result.
When you write `/produkty-buty/` or `/produkty-produkt:buty.html` for search are two different phrase, but result is similar because search engine optimize itself.
This case concerns all examples your wrote and you should disallowed index in robot.txt this results.

To show list of products for example `/produkty-sukienki-i-koszulki-erotyczne` you should go to category: `/kategoria-sukienki-i-koszulki-erotyczne/`

Time to time some product disappear for catalog (eg: `klapki-damskie/espadryle-tommy-hilfiger-emma-7d-fw56820665-black-990-508bbc5f1794c49ae6189ac2c6f67860`), then this project redirects to search `/produkty-klapki-damskie/espadryle-tommy-hilfiger-emma-7d-fw56820665-black-990-508bbc5f1794c49ae6189ac2c6f67860` to show client similar products.

**Comment by adrianpaz** [comment]
Thank You
